name: Linters
run-name: ${{ github.actor }} push code in the PR of "${{ github.head_ref }}" branch
on:
    pull_request:
        paths:
            - '**.php'
            - '**.vue'
            - '**.js'
concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

jobs:
    php:
        runs-on: ubuntu-20.04
        steps:
            -   name: Check out repository code
                uses: actions/checkout@v4
            -   name: Install composer dependencies
                run: composer install
            -   name: Run PHP Stan
                run: composer run phpstan
            -   name: Run PHP CS
                run: composer run phpcs
    vue:
        runs-on: ubuntu-latest
        steps:
            -   name: Check out repository code
                uses: actions/checkout@v4
            -   name: Setup Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}
            -   name: npm ci
                run: npm ci
            -   name: Run ES Lint
                run: npm run lint