root: true
extends:
    - airbnb-base
    - plugin:vue/vue3-essential
    - plugin:@intlify/vue-i18n/recommended
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - vue
settings:
    import/core-modules:
      - '@intlify/unplugin-vue-i18n/messages'
    vue-i18n:
      localeDir: './assets/locales/*.{json}'
      messageSyntaxVersion: '^9.0.0'
rules:
    # Vanilla JS rules
    indent:
        - error
        - 4
    max-len:
        - warn
        -   ignoreComments: true
            code: 250
    import/prefer-default-export:
        - off
    # VueJS rules
    vue/html-indent:
        - error
        - 4
    # Vue I18n rules
#    '@intlify/vue-i18n/no-raw-text':
#      - error
#          -   ignoreNodes:
#          - x-icon
