services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '8080:80'
        depends_on:
            - php
    php:
        build:
            context: ./.docker
            dockerfile: ./Dockerfile
        volumes:
            - ./:/var/www/html
        environment:
            PHP_IDE_CONFIG: serverName=docker
        depends_on:
            - database
    database:
        image: postgres:16
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: database
        volumes:
            - database_data:/var/lib/postgresql/data:rw
        ports:
            - '5432:5432'
    vite:
        image: node:alpine
        working_dir: /usr/app
        user: 1000:1000
        volumes:
            - ./:/usr/app
        command: npm run dev -- --host
        ports:
            - "5173:5173"
volumes:
    database_data: